---
# dependency for Ansible to work on new CentOS/RedHat host

# Python2 support
- name: If missing, install Python2
  raw: test -e /usr/bin/python || (yum -y update && yum install -y python)
  changed_when: False
- setup: # aka gather_facts: yes

# Python3 
- name: If missing, install Python3
  raw: test -e /usr/bin/python3 || (yum -y update && yum install -y python3)
  changed_when: False
- setup: # aka gather_facts: yes


