---
# Dependency for Ansible to work on new Ubuntu/Debian/CentOS/RedHat host

# Python2 for apt systems
- name: If missing, install Python2 for Ubuntu/Debian
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
  changed_when: False
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial') or
        (ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch')

# Python2 for yum systems 
- name: If missing, install Python2 for CentOS/RedHat
  raw: test -e /usr/bin/python || (yum -y update && yum install -y python)
  changed_when: False
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

# Python3 for apt systems 
- name: If missing, install Python3 for Ubuntu/Debian
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
  changed_when: False

# Python for yum systems 
- name: If missing, install Python3 for CentOS/RedHat
  raw: test -e /usr/bin/python3 || (yum -y update && yum install -y python3)
  changed_when: False
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'


